__tests__/components/PromptCollection.test.tsx, app/browse/page.tsx, app/page.tsx, components/PromptCollection.tsx, middleware.ts
Redesign of home page using grids instead of plain containers
=> feat: style homepage

__tests__/components/Prompt.test.tsx, __tests__/components/PromptCollection.test.tsx, __tests__/hooks/usePromptCollection.test.ts, app/browse/my/page.tsx, app/browse/page.tsx, app/page.tsx, components/PromptCollection.tsx, hooks/usePromptCollection.ts, models/PromptViewModel.ts, utils/formatters.ts
Implements filter capabilities in the browse section to filter prompts by category or sdlc phase
Fixes #7 
=> feat: filter prompts

__tests__/components/PromptCollection.test.tsx, components/PromptCollection.tsx, components/TopNav.tsx, repositories/PromptRepository.ts
Allow users to search for prompts by name. 
Fixes #6 
=> feat: search for prompts

app/browse/my/page.tsx
=> feat: harmonize layout of my prompts with general browse section

__tests__/components/HomeHeader/HomeHeader.test.tsx, app/browse/my/page.tsx, app/browse/page.tsx, app/page.tsx, components/HomeHeader/HomeHeader.tsx, components/HomeHeader/styles.modules.css, components/PromptCollection.tsx
=> feat: integrate search in home

__tests__/components/PromptCollection.test.tsx, app/browse/page.tsx, app/layout.tsx, components/PromptCollection.tsx
=> fix: missing suspense boundary when dealing with useSearchParam

__tests__/components/Prompt.test.tsx, __tests__/components/PromptCollection.test.tsx, __tests__/components/PromptForm.test.tsx, __tests__/models/PromptViewModel.test.ts, components/Prompt.tsx, components/PromptCollection.tsx, components/PromptForm.tsx, models/PromptViewModel.ts, package-lock.json, package.json, vitest.setup.js
=> feat: prompt form validation

__tests__/components/PromptForm.test.tsx, components/PromptForm.tsx, repositories/PromptRepository.ts
=> feat: allow users to delete a prompt

__tests__/components/TopNav.test.tsx, components/TopNav.tsx
=> feat: add feedback link to top navigation

app/layout.tsx
=> fix: metadata base to promptz.dev

amplify/auth/email-templates.ts, amplify/auth/resource.ts
=> feat: moving to production using SES for cognito

app/prompt/[id]/opengraph-image.tsx
=> style: update prompt og-image with new aligned logo

__tests__/components/DraftCollection.test.tsx, __tests__/components/PromptForm.test.tsx, __tests__/models/PromptViewModel.test.ts, components/DraftCollection.tsx, components/PromptForm.tsx, models/PromptViewModel.ts
=> fix: prompts not deleted

__tests__/components/Prompt.test.tsx, __tests__/components/PromptForm.test.tsx, __tests__/models/PromptViewModel.test.ts, amplify/data/resource.ts, app/globals.css, components/Prompt.tsx, components/PromptForm.tsx, models/PromptViewModel.ts, repositories/PromptRepository.ts
=> feat: allow users to document prompt usage

amplify/backend.ts
=> feat: enable appsync logging with custom metric filter

amplify/backend.ts
=> release: public launch

app/layout.tsx, components/Footer.tsx
=> feat: add footer with SEO texts and relevant links

amplify/backend.ts, app/layout.tsx, components/Footer.tsx
=> release: v.1.0

.github/workflows/pr-lint.yml
Introduces a new workflow to verify the PR title is following the conventional commits spec
=> ci: add workflow to lint pull request titles

__tests__/components/PromptForm.test.tsx, __tests__/utils/formatters.test.ts, utils/formatters.ts
Renders descriptions on SDLC phase selections to support users in deciding what SDLC phase to use. 
Fixes #50 
=> feat: show descriptions for each SDLC phase in prompt form

README.md, amplify/auth/resource.ts, amplify/backend.ts, package.json
Provides instructions and npm script to create a sandbox environment in AWS accounts that are not owned by PROMPTZ. 
Fixes #55 
=> feat: sandbox configuration for external AWS accounts

.github/workflows/ci.yml, __tests__/robots.test.ts, __tests__/sitemap.test.ts, app/robots.ts, app/sitemap.ts, models/PromptViewModel.ts
Add new endpoints and functionality for robots.txt and sitemap.xml to improve SEO capabilities.
- Create robots.txt endpoint with corresponding tests
- Implement sitemap.xml generation with test coverage
- Update PromptViewModel to support new SEO features
Fixes #62 
=> feat(seo): implement robots.txt and sitemap.xml

app/globals.css, components/Prompt.tsx, package-lock.json, package.json
- Update Prompt.tsx component
- Modify global CSS styles
- Update package dependencies
Fixes #67 
=> feat: enhance prompt component styling and dependencies by rendering markdown

__tests__/components/PromptForm.test.tsx, __tests__/models/PromptViewModel.test.ts, app/prompt/[id]/edit/page.tsx, app/prompt/create/page.tsx, components/PromptForm.tsx, models/PromptViewModel.ts, utils/formatters.ts
- Transform Agent support
- Fullscreen mode
- Context Modifier Shortcuts to add them to the prompts and create awareness what context modifier can be used in what client
- Auto-Prepend of /dev and /transform when publishing a prompt or saving a draft
- 
=> feat: editor improvements

__tests__/models/PromptViewModel.test.ts, components/PromptForm.tsx, models/PromptViewModel.ts, utils/formatters.ts
AWS launched new agent capabilities. With this PR, users can select either the new test, review or doc agent and submit prompts for this agent. 
=> feat: add support for test, review and doc agents
